import cv2

class Nada:
    """
    An OpenCV pipeline generated by GRIP.
    """
    
    def __init__(self):
        """initializes all values to presets or None if need to be set
        """

    def process(self, source0):
        """
        Runs the pipeline and sets all outputs to new values.
        """
        
        # Draw thin line down center of screen
        cv2.line(source0,(320/2,0),(320/2,240),(0,255,0),1)